name: R pkgdown multisite docs
author: Insights Engineering
description: Github Action that generates multisite R documentation created with pkgdown. Modification is done on previously generated gh-pages branch
inputs:
  path:
    description: Path to package's root
    required: false
    default: "."
  release_name:
    description: latest/main, pre-release or new_tag_string (e.g. "v0.8.0") which will be used for R script to change links
    required: true
    default: "main"
runs:
  using: 'composite'
  steps:
    - run: |
        cd ${{ inputs.path }} 
        pwd 
        ls -alh
        Rscript ${{ github.action_path }}pkgdown-multisite.R ${{ inputs.release_name }}
      shell: bash