name: R pkgdown Multi Version docs
author: Insights Engineering
description: Generates multisite R documentation created with pkgdown.
branding:
  icon: 'anchor'
  color: 'orange'
inputs:
  path:
    description: Path to package's root
    required: false
    default: "."
  default-landing-page:
    description: |
      The default branch or tag on gh-pages that corresponds to the landing page.
      For instance, if your root index page on gh-pages is built using the 'main'
      branch, then the root page of the website will correspond to this page.
      If 'latest-tag' is selected, then the latest version will become the default.
    default: main
    required: false
  branches-or-tags-to-list:
    description:
      Which branches or tags should be listed under the
      'Versions' dropdown menu on the landing page?
      This input should be a regular expression in R.
    required: false
    default: >-
      ^main$|^devel$|^pre-release$|^latest-tag$|^release-candidate$|^develop$|^v([0-9]+\\.)?([0-9]+\\.)?([0-9]+)|^v([0-9]+\\.)?([0-9]+\\.)?([0-9]+)(-rc[0-9]+)$
  insert-after-section:
    description:
      After which section in the navbar should the 'Versions'
      dropdown be added? Choose between 'Reference' and 'Changelog'
      for the surest of choices.
    required: false
    default: Changelog
  version-tab:
    description: |
      Configuration how should the dropdownlist appear for multiple versions.
      It should be set as an ASCII text representation of an R list object
      Example:
      """
      list(config = list(
        tooltip = list(
          main = "Tooltip for main branch"
        ),
        text = list(
          main = "main branch"
        )
      ))
      """
      String should be quoted with " sign
    required: false
    default: ""
  refs-order:
    description: |
      The order in which refs should appear in the drop-down list. Versions not in the vector
      will appear below refs listed here.
      If docs have never been generated for the ref, the ref will not appear in the
      drop-down. Similarly, if docs have been generated for the ref, but the ref is not
      listed in the vector, it will not appear in the drop-down.
      Example:
      c("main", "devel", "pre-release", "latest-tag")
    required: false
    default: c("main", "devel", "pre-release", "latest-tag")
  latest-tag-alt-name:
    description: An alternate name for the 'latest-tag' item
    required: false
    default: ''
  release-candidate-alt-name:
    description: An alternate name for the 'release-candidate' item
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Create copy of latest tag
      run: |
        cd ${{ inputs.path }}
        set +o pipefail
        latest_tag=$(ls -1d * \
          | grep -E "^v([0-9]+\.)?([0-9]+\.)?([0-9]+)$" \
          | sort -t "." -k1,1n -k2,2n -k3,3n \
          | tail -1)
        latest_rc_tag=$(ls -1d * \
          | grep -E "^v([0-9]+\.)?([0-9]+\.)?([0-9]+)(-rc[0-9]+)$" \
          | sort -t "." -k1,1n -k2,2n -k3,3n \
          | tail -1)
        set -o pipefail
        rm -rf latest-tag
        rm -rf release-candidate
        [[ "${latest_tag}" != "" ]] \
          && cp -r "${latest_tag}" latest-tag \
          || echo "No latest tag found, not creating directory for latest-tag"
        [[ "${latest_rc_tag}" != "" ]] \
          && cp -r "${latest_rc_tag}" release-candidate \
          || echo "No release candidate tag found, not creating directory for release-candidate"
        if [[ "${{ inputs.latest-tag-alt-name }}" != "" && -d latest-tag ]]
        then {
          rm -rf ${{ inputs.latest-tag-alt-name }}
          cp -r latest-tag ${{ inputs.latest-tag-alt-name }}
        }
        fi
        if [[ "${{ inputs.release-candidate-alt-name }}" != "" && -d release-candidate ]]
        then {
          rm -rf ${{ inputs.release-candidate-alt-name }}
          cp -r release-candidate ${{ inputs.release-candidate-alt-name }}
        }
        fi
      shell: bash

    - name: Create redirect page
      run: |
        cd ${{ inputs.path }}
        cp "${GITHUB_ACTION_PATH}/redirect.html" index.html
        perl -p -i -e \
          "s@DEFAULT_LANDING_PAGE@${{ inputs.default-landing-page }}@g" \
          index.html
        perl -p -i -e \
          "s@REPOSITORY@${{ github.event.repository.name }}@g" \
          index.html
        perl -p -i -e \
          "s@OWNER@${{ github.repository_owner }}@g" \
          index.html
        touch .nojekyll
      shell: bash

    - name: Add drop-down to docs
      run: |
        # TODO parametrize
        python r-pkgdown-multiversion/core.py . \
          --pattern '^main$|^devel$|^pre-release$|^latest-tag$|^release-candidate$|^develop$|^v([0-9]+\\.)?([0-9]+\\.)?([0-9]+)|^v([0-9]+\\.)?([0-9]+\\.)?([0-9]+)(-rc[0-9]+)$' \
          --refs_order main latest-tag --n 1
          --base_url https://insightsengineering.github.io/teal/
      shell: bash

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[actions skip] Built site for ${{ github.event.repository.name }}@${{ github.sha }}"
        repository: ${{ inputs.path }}
        commit_user_name: github-actions
        commit_user_email: 41898282+github-actions[bot]
        branch: gh-pages
        create_branch: true
