---
name: Test action for multisite pkgdown

on:
  push:
    tags:
      - "v*"
    branches:
      - main
  pull_request:
    branches:
        - main

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    name: Test multisite change creation
    container:
      image: ghcr.io/insightsengineering/verse_4.1.0_bioc_3.13:latest
    steps:
      - name: Checkout multisite action repo
        uses: actions/checkout@v2

      - name: Checkout R package repo
        uses: actions/checkout@v2
        with:
          repository: "Roche/rtables"
          path: "rtables"
          ref: "gh-pages"

      - name: Test multisite repo
        uses: ./
        with:
          path: "rtables"
          release_name: "latest"

      - name: Show result
        run: |
          pwd
          ls -al 
          cd rtables
          if [ `git diff | wc -l` != 0 ]
              then
              git diff --name-only
              else
                echo "No changes detected"
                return -1
          fi
        shell: sh
